### ISSUE TITLE
deploy failed

### ISSUE THREAD

**Issue by xiangjie256329** [tact-lang/tact-template#37]
git clone https://github.com/tact-lang/tact-template test-template
cd test-template/
yarn
yarn test
yarn build
yarn lint
yarn deploy

then,deploy fail,I didn't change a single line of code:

Uploading package...
/Users/xj/code/defi/games/dst/tact/test-template/node_modules/zod/lib/types.js:43
                const error = new ZodError_1.ZodError(ctx.common.issues);
                              ^
ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]
    at Object.get error [as error] (/Users/xj/code/defi/games/dst/tact/test-template/node_modules/zod/lib/types.js:43:31)
    at ZodObject.parse (/Users/xj/code/defi/games/dst/tact/test-template/node_modules/zod/lib/types.js:143:22)
    at fetchBackend (/Users/xj/code/defi/games/dst/tact/test-template/node_modules/@tact-lang/deployer/src/deployer.ts:18:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepareTactDeployment (/Users/xj/code/defi/games/dst/tact/test-template/node_modules/@tact-lang/deployer/src/deployer.ts:31:19)
    at async /Users/xj/code/defi/games/dst/tact/test-template/sources/contract.deploy.ts:21:19 {
  issues: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'string',
      path: [],
      message: 'Expected object, received string'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'string',
      path: [],
      message: 'Expected object, received string'
    }
  ]
}

**Comment by Nik20f** [comment]
Uploading package...
/Users/xj/code/defi/games/dst/tact/test-template/node_modules/zod/lib/types.js:43
const error = new ZodError_1.ZodError(ctx.common.issues);
^
ZodError: [
{
"code": "invalid_type",
"expected": "object",
"received": "string",
"path": [],
"message": "Expected object, received string"
"naim.4:{354565.88.7} =36/85/(www.vork.)
"Yong.4:{354565.88.8} =36/85 www/000
"sudo apt-get update
"sudo apt-get install -y build-essential git cmake ninja-build zlid1g-dev"

**Comment by HaloLyyL** [comment]
I got the same problem,are you fix it?

**Comment by i582** [comment]
Hey, is this problem still there even after trying a few times? It looks like GitHub is sending back some text instead of the configuration with the server URLs in JSON
