### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by longerd** [tact-lang/tact-template#38]
➜  tact-template git:(tact-release-1.5.0) ✗ yarn build   
```
yarn run v1.22.22
$ tact --config ./tact.config.json
💼 Compiling project sample...
Tact compilation failed
Error: Line 33, col 9:
  32 |         self.add(1);
> 33 |         self.reply("incremented".asComment());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  34 |     }
Type "SampleTactContract" does not have a function named "reply"
    at throwError (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/grammar/ast.js:49:11)
    at resolveCall (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/types/resolveExpression.js:264:34)
    at resolveExpression (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/types/resolveExpression.js:393:16)
    at processStatements (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/types/resolveStatements.js:80:61)
    at resolveStatements (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/types/resolveStatements.js:195:19)
    at precompile (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/pipeline/precompile.js:91:53)
    at build (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/pipeline/build.js:34:43)
    at Object.compileProjects (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/main.js:49:33)
    at /home/longer/workspace/private/tact-template/node_modules/ton-tact/bin/tact:18:20
    at Object.<anonymous> (/home/longer/workspace/private/tact-template/node_modules/ton-tact/bin/tact:23:3)
Done in 0.44s.
```

**Comment by longerd** [comment]
also it seems that tact doesn't suppoort `+=` operator
➜  tact-template git:(tact-release-1.5.0) ✗ yarn build
```
yarn run v1.22.22
$ tact --config ./tact.config.json
💼 Compiling project sample...
Tact compilation failed
Error: Line 24, col 23:
  23 |         // Update counter
> 24 |         self.counter += v;
                             ^
  25 |     }
Expected "\"", "initOf", "null", "_", "A".."Z", "a".."z", "false", "true", a digit, "0X", "0x", "(", "!", "+", or "-"
    at parse (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/grammar/grammar.js:538:15)
    at parseImports (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/grammar/grammar.js:545:13)
    at processImports (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/pipeline/precompile.js:55:46)
    at precompile (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/pipeline/precompile.js:73:5)
    at build (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/pipeline/build.js:34:43)
    at Object.compileProjects (/home/longer/workspace/private/tact-template/node_modules/ton-tact/dist/main.js:49:33)
    at /home/longer/workspace/private/tact-template/node_modules/ton-tact/bin/tact:18:20
    at Object.<anonymous> (/home/longer/workspace/private/tact-template/node_modules/ton-tact/bin/tact:23:3)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
Done in 0.18s.
```

**Comment by anton-trunov** [comment]
Did you do `yarn install` before trying to build your contract?

**Comment by longerd** [comment]
> Did you do `yarn install` before trying to build your contract?

It works well. Thanks
